name: Create and publish a package
on:
  release:
    types: [created]
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        #repository: ${{ github.repository }}/pixel-it-discord-bot
        repository: o0shojo0o/pixel-it-discord-bot-
        tag_with_sha: true
        tag_with_ref: true
