name: Create and publish a package
on:
  release:
    types: [created]
jobs:
  run-npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: |
          npm install
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: public/

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: run-npm-build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        #repository: ${{ github.repository }}/pixel-it-discord-bot-image
        repository: pixel-it-discord-bot-image/pixel-it-discord-bot-image
        tag_with_sha: true
        tag_with_ref: true
